2-1

In [ ]:
print('학생 그룹 점수의 합계와 평균을 구합니다.')

score1 = int(input('1번 학생의 점수를 입력.:'))
score2 = int(input('2번 학생의 점수를 입력.:'))
score3 = int(input('3번 학생의 점수를 입력.:'))
score4 = int(input('4번 학생의 점수를 입력.:'))
score5 = int(input('5번 학생의 점수를 입력.:'))

total = 0
total += score1
total += score2
total += score3
total += score4
total += score5

print(f'합계는 {total}')
print(f'평균은 {total / 5}')

학생 그룹 점수의 합계와 평균을 구합니다.
1번 학생의 점수를 입력.:1
2번 학생의 점수를 입력.:2
3번 학생의 점수를 입력.:3
4번 학생의 점수를 입력.:4
5번 학생의 점수를 입력.:5
합계는 15
평균은 3.0

2-2

In [ ]:
from typing import Any, Sequence

def max_of(a: Sequence) -> Any:
    maximum =a[0]
    for i in range(1, len(a)):
        if a[i] > maximum:
            maximum = a[i]
    return maximum

if __name__ == '__main__':
    print('배열의 최댓값을 구함')
    num = int(input('원소 수 입력: '))
    x= [None] * num

    for i in range(num):
        x[i] = int(input(f'x[{i}]값 입력: '))

    print(f'{max_of(x)}')

배열의 최댓값을 구함
원소 수 입력: 5
x[0]값 입력: 0
x[1]값 입력: 0
x[2]값 입력: 5
x[3]값 입력: 3
x[4]값 입력: 1
5

2-3

In [ ]:
from max import max_of

print('배열의 최댓값\nend 입력시 종료')

number = 0
x=[]

while True:
    s = input(f'x[{number}]값 입력: ')
    if s == 'end':
        break
    x.append(int(s))
    number += 1

print(f'{number}개 중 최댓값은 {max_of(x)}')

배열의 최댓값
end 입력시 종료
x[0]값 입력1
x[1]값 입력2
x[2]값 입력3
x[3]값 입력end
3개 중 최댓값은 3

2-4

In [ ]:
import random
from max import max_of

print('난수의 최댓값 구하기')
num = int(input('난수의 개수: '))
lo = int(input('최소난수: '))
hi = int(input('최대난수: '))
x = [None] * num

for i in range(num):
    x[i] = random.randint(lo, hi)

print(f'{x}')
print(f'이 가운데 최대값은 {max_of(x)}')

난수의 최댓값 구하기
난수의 개수: 5
최소난수: 1
최대난수: 99
[6, 1, 36, 17, 41]
이 가운데 최대값은 41

2-5

In [ ]:
from max import max_of

t = (4, 7, 5.6, 2, 3.14, 1)
s = 'string'
a = ['DTS', 'AAC', 'FLAC']

print(f'{t}의 최대값 {max_of(t)}')
print(f'{s}의 최댓값 {max_of(s)}')
print(f'{a}의 최대값 {max_of(a)}')

(4, 7, 5.6, 2, 3.14, 1)의 최대값 7
string의 최댓값 t
['DTS', 'AAC', 'FLAC']의 최대값 FLAC

2-6

In [71]:
from typing import Any, MutableSequence

def reverse_array(a:MutableSequence) -> None:
    n = len(a)
    for i in range(n // 2):
        a[i], a[n - i - 1] = a[n - i - 1], a[i]

if __name__ == '__main__':
    print('배열을 역순으로 정렬')
    nx = int(input('원소 수 입력: '))
    x = [None] * nx

    for i in range(nx):
        x[i] = int(input(f'x[{i}]값 입력: '))

    reverse_array(x)

    for i in range(nx):
        print(f'x[{i}] = {x[i]}')

배열을 역순으로 정렬
원소 수 입력: 5
x[0]값 입력: 1
x[1]값 입력: 2
x[2]값 입력: 3
x[3]값 입력: 4
x[4]값 입력: 5
x[0] = 5
x[1] = 4
x[2] = 3
x[3] = 2
x[4] = 1

2-7

In [77]:
def card_conv(x: int, r: int) -> str:
    d = ''
    dchar = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

    while x > 0:
        d += dchar[x % r]
        x //= r
    return d[::-1]

if __name__ == '__main__':
    print('10진수를 n진수로 변환')
    while True:
        while True:
            no = int(input('변환할 값으로 음이아닌 정수 입력: '))
            if no > 0:
                break

        while True:
            cd = int(input('몇 진수로 변환할지 입력: '))
            if 2 <= cd <= 36:
                break

        print(f'{cd}진수로는 {card_conv(no, cd)}')

        retry = input('한번더? (Y / N): ')
        if retry in {'N', 'n'}:
            break

10진수를 n진수로 변환
변환할 값으로 음이아닌 정수 입력: 10
몇 진수로 변환할지 입력: 2
2진수로는 1010
한번더? (Y / N)n

2-8

In [78]:
counter = 0

for n in range(2, 1001):
    for i in range(2, n):
        counter += 1
        if n % i == 0:
            break

    else:
        print(n)

print(f'나눗셈을 실행한 횟수 {counter}')

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997
나눗셈을 실행한 횟수 78022

2-9

In [82]:
counter = 0
ptr = 0
prime = [None] * 500

prime[ptr] = 2
ptr += 1

for n in range(3, 1001, 2):
    for i in range(1, ptr):
        counter += 1
        if n % prime[i] == 0:
            break
    else:
        prime[ptr] = n
        ptr += 1

print(prime[:ptr])
print(counter)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
14622

2-10

In [84]:
counter = 0
ptr = 0
prime = [None] * 500

prime[ptr] = 2
ptr += 1

prime[ptr] = 3
ptr += 1

for n in range(5, 1001, 2):
    i = 1
    while prime[i] * prime[i] <= n:
        counter += 2
        if n % prime[i] == 0:
            break
        i += 1
    else:
        prime[ptr] = n
        ptr += 1
        counter += 1

print(prime[:ptr])
print(counter)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
3774